version: '3.9'

networks:
  sharelatex-internal: {}

services:
  sharelatex:
    image: 'sharelatex/sharelatex:${SHARELATEX_IMAGE_VERSION:-3.5}'
    depends_on:
      - 'sharelatex-mongo'
      - 'sharelatex-redis'
    environment:
      REDIS_HOST: 'sharelatex-redis'
      SHARELATEX_ADMIN_EMAIL: '${ROOT_EMAIL:-changeme@changeme.org}'
      SHARELATEX_APP_NAME: '${USERNAME} ShareLaTeX'
      # SHARELATEX_HEADER_IMAGE_URL: 'http://somewhere.com/mylogo.png'
      SHARELATEX_MONGO_URL: 'mongodb://sharelatex-mongo/sharelatex'
      SHARELATEX_NAV_TITLE: '${SITE:-localhost} - ShareLaTeX'
      SHARELATEX_REDIS_HOST: 'sharelatex-redis'
      SHARELATEX_SITE_URL: 'https://latex.${SITE:-localhost}'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
    labels:
      traefik.enable: true
      traefik.http.routers.sharelatex.rule: 'Host(`sharelatex.${SITE:-localhost}`)'
      traefik.http.services.sharelatex.loadbalancer.server.port: 80
    networks:
      - 'sharelatex-internal'
      - 'srv'
    restart: 'always'
    volumes:
      - './data:/var/lib/sharelatex'

  sharelatex-mongo:
    image: 'mongo:4.0'
    healthcheck:
      test: ['CMD', 'echo', 'db.runCommand("ping").ok',
             '|', 'mongo', 'localhost:27017/test', '--quiet']
    labels:
      traefik.enable: false
    networks:
      - 'sharelatex-internal'
    restart: 'always'
    volumes:
      - './mongo:/data/db'

  sharelatex-redis:
    image: 'redis:6.0-alpine'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    labels:
      traefik.enable: false
    networks:
      - 'sharelatex-internal'
    restart: 'always'
    volumes:
      - './redis:/data'
