version: '3.9'

services:
  nginx:
    image: 'nginx:${NGINX_IMAGE_VERSION:-stable-alpine}'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: 'Host(`${SITE:-localhost}`)'
      traefik.http.services.nginx.loadbalancer.server.port: 80
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './conf:/etc/nginx/conf.d'
      - './logs:/var/log/nginx/'