version: '3.9'

services:
  portfolio:
    image: 'amitkurud/portfolio:${PORTFOLIO_IMAGE_VERSION:-latest}'
    environment:
      PROMETHEUS_ENABLED: '${PORTFOLIO_PROMETHEUS_ENABLED:-false}'
      TIME_ZONE: '${TZ:-Europe/Paris}'
    labels:
      traefik.enable: true
      traefik.http.routers.ciao.rule: 'Host(`${PORTFOLIO_SITE:-localhost}`)'
      traefik.http.services.ciao.loadbalancer.server.port: 80
    networks:
      - 'srv'
    restart: 'always'