version: '3.9'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_IMAGE_VERSION:-7.1.0}'
    environment:
      ES_JAVA_OPTS: '${ELASTICSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}'
      bootstrap.memory_lock: '${ELASTICSEARCH_MEMORY_LOCK:-true}'
      cluster.name: '${ELASTICSEARCH_CLUSTER_NAME:-docker-cluster}'
      discovery.type: '${ELASTICSEARCH_DISCOVERY_TYPE:-single-node}'
    labels:
      traefik.enable: false
    restart: 'always'
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - './elasticsearch/data:/usr/share/elasticsearch/data'

  kibana:
    image: 'docker.elastic.co/kibana/kibana:${KIBANA_IMAGE_VERSION:-7.1.0}'
    labels:
      traefik.enable: true
      traefik.http.routers.kibana.middlewares: 'basic_auth@docker'
      traefik.http.routers.kibana.rule: 'Host(`kibana.${SITE:-localhost}`)'
      traefik.http.services.kibana.loadbalancer.server.port: 5601
    links:
      - 'elasticsearch'
    networks:
      - 'srv'
    restart: 'always'
    volumes:
      - './kibana/kibana.yml:/usr/share/kibana/config/kibana.yml'

  logstash:
    image: 'docker.elastic.co/logstash/logstash:${LOGSTASH_IMAGE_VERSION:-7.1.0}'
    labels:
      traefik.enable: false
    links:
      - 'elasticsearch'
    restart: 'always'
    volumes:
      - './logstash/:/usr/share/logstash/pipeline/'
      - '../nginx/logs:/var/log/nginx'
      - '../traefik/logs:/var/log/traefik'
