version: '3.9'

services:
  it-tools:
    container_name: it-tools
    image: ghcr.io/corentinth/it-tools:latest
    environment:
      PROMETHEUS_ENABLED: '${TOOLS_PROMETHEUS_ENABLED:-false}'
      TIME_ZONE: '${TZ:-Europe/Paris}'
    labels:
      traefik.enable: true
      traefik.http.routers.ittools.middlewares: 'basic_auth@docker'
      traefik.http.routers.ittools.rule: 'Host(`tools.${SITE:-localhost}`)'
      traefik.http.services.ittools.loadbalancer.server.port: 80
    restart: unless-stopped